format_version: 10
environments:
  sdk-environment:
    secure_variables:
      GITHUB_TOKEN: "{{SECRET:[github-secrets][token]}}"
    pipelines:
      - langquence-dev-deploy-pipeline
pipelines:
  langquence-dev-deploy-pipeline:
    group: defaultGroup
    display_order: 10
    lock_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/Langquence/langquence-was.git
        branch: feat/add-sdk-generate-pipeline
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            setUp:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "${GITHUB_TOKEN}"
                # - exec:
                #     command: docker
                #     arguments:
                #       - rm
                #       - -f
                #       - langquence-was-dev
                # - exec:
                #     command: sh
                #     arguments:
                #       - -c
                #       - cp /home/go/.env .env
                # - exec:
                #     command: docker
                #     arguments:
                #       - build
                #       - -t
                #       - langquence-was-dev:local
                #       - .
                # - exec:
                #     command: docker
                #     arguments:
                #       - run
                #       - -d
                #       - --name
                #       - langquence-was-dev
                #       - -p
                #       - 8090:8090
                #       - --env-file
                #       - .env
                #       - langquence-was-dev:local